pdr:
  version: "1.0"
  setup:
    time:
      calibrate: 9.606
      start: 878928
      end: 1035128
    measurements: &measurement_
      file_path: ""
      column_style:
        - "time"
        - "gx"
        - "gy"
        - "gz"
        - "ax"
        - "ay"
        - "az"
      thresholds:
        min_count: 800
        reverse_data_len: 800
  sampling: &sampling
    rate: 100
  step_detection:
    measurements: *measurement_
    beta: 0.1
    epsilon: 0.001
    sampling: *sampling
    accelerometer:
      lpf:
        cutoff_hz: 2.0
        order: 2.0
    thresholds:
      grad: 0.1
      time_length_factor:
        min: 0.3
        max: 0.8
    gravity: 9.7
    k: 5.1
